### ISSUE TITLE
Сборка для OSX

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/club#10]

**Comment by morevnaproject** [comment]
Проверил на OSX Moluntain Lion - работает! Ура!

**Comment by morevnaproject** [comment]
@blackwarthog отгрузи, пожалуйста, на Gumroad. ^__^

**Comment by blackwarthog** [comment]
Отгрузил

**Comment by morevnaproject** [comment]
Спасибо! ^__^

**Comment by morevnaproject** [comment]
https://morevnaproject.org/2017/08/08/opentoonz-morevna-edition-now-available-osx/
