### ISSUE TITLE
Путаница во время скачивание

### ISSUE THREAD

**Issue by Agnyy** [morevnaproject/club#12]
Название файла слишком длинное и не видно где 32 битное, а где 64 

![image](https://user-images.githubusercontent.com/25137502/28996926-38e1d400-7a12-11e7-9494-51491aa24e99.png)

**Comment by morevnaproject** [comment]
@blackwarthog исправил.
@Agnyy всё ли нормально теперь?

**Comment by Agnyy** [comment]
Вот теперь всё видно) но мне кажется текст очень длинный, я бы приставку win64 - win32 в самый перёд поставил, а то глазами искать приходиться) Хотя это мелочи) 

![image](https://user-images.githubusercontent.com/25137502/29488218-2eee5060-850f-11e7-862b-1cf9310ba777.png)
